title: My Awesome Website
description: A brief description of your website
author: Your Name
baseurl: "" # Set to your subdirectory if necessary
url: https://yourwebsite.com # Replace with your website's URL

# Jekyll Build Settings
markdown: kramdown
safe: true
exclude:
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
